image: gitpod/workspace-flutter
ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - command: echo "TODO ADD START TASKS"
vscode:
  extensions:
    - Dart-Code.flutter@3.9.1:Vg9YBnZuZPBIetUV1bObAQ==
    - Dart-Code.dart-code@3.9.1:jTAh+eEdGYiGfXpp+cNFlg==
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addCheck: true
    addBadge: true
    addLabel: true
